### ISSUE TITLE
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

### ISSUE THREAD

**Issue by andyyuan78** [jclevesque/bagged-budget-svms#1]
ubgpu@ubgpu:~/github/bagged-budget-svms/samples$ python a9a.py 
Traceback (most recent call last):
  File "a9a.py", line 37, in <module>
    num_procs=multiprocessing.cpu_count() #number of processes for training and testing
  File "/usr/local/lib/python3.4/dist-packages/bbsvm/bsgd_ensemble.py", line 67, in **init**
    os.makedirs(output_folder, exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
ubgpu@ubgpu:~/github/bagged-budget-svms/samples$ 
ubgpu@ubgpu:~/github/bagged-budget-svms/samples$

**Comment by jclevesque** [comment]
You have two options. You can remove the exist_ok argument and wrap the function call in a try/except, like so : 

```
try:
    os.makedirs(output_folder)
except FileExistsError as exc:
    pass
```

or you could upgrade to a more recent version of python (the exist_ok parameter was added in python 3.2). 

Sorry for the delay!

**Comment by andyyuan78** [comment]
~~strange:

ubgpu@ubgpu:~/github/bagged-budget-svms/samples$ python3 a9a.py
Traceback (most recent call last):
  File "a9a.py", line 28, in <module>
    import multiprocessing
  File "/usr/lib/python3.4/multiprocessing/**init**.py", line 16, in <module>
    from . import context
  File "/usr/lib/python3.4/multiprocessing/context.py", line 3, in <module>
    import threading
  File "/usr/lib/python3.4/threading.py", line 10, in <module>
    from traceback import format_exc as _format_exc
  File "/usr/lib/python3.4/traceback.py", line 3, in <module>
    import linecache
  File "/usr/lib/python3.4/linecache.py", line 10, in <module>
    import tokenize
  File "/usr/lib/python3.4/tokenize.py", line 29, in <module>
    import collections
  File "/usr/lib/python3.4/collections/__init__.py", line 17, in <module>
    from reprlib import recursive_repr as _recursive_repr
  File "/usr/local/lib/python2.7/dist-packages/reprlib/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
    if not enabled():
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
    import re
  File "/usr/lib/python3.4/re.py", line 324, in <module>
    import copyreg
  File "/usr/local/lib/python2.7/dist-packages/copyreg/**init**.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.

Original exception was:
Traceback (most recent call last):
  File "a9a.py", line 28, in <module>
    import multiprocessing
  File "/usr/lib/python3.4/multiprocessing/**init**.py", line 16, in <module>
    from . import context
  File "/usr/lib/python3.4/multiprocessing/context.py", line 3, in <module>
    import threading
  File "/usr/lib/python3.4/threading.py", line 10, in <module>
    from traceback import format_exc as _format_exc
  File "/usr/lib/python3.4/traceback.py", line 3, in <module>
    import linecache
  File "/usr/lib/python3.4/linecache.py", line 10, in <module>
    import tokenize
  File "/usr/lib/python3.4/tokenize.py", line 29, in <module>
    import collections
  File "/usr/lib/python3.4/collections/__init__.py", line 17, in <module>
    from reprlib import recursive_repr as _recursive_repr
  File "/usr/local/lib/python2.7/dist-packages/reprlib/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
ubgpu@ubgpu:~/github/bagged-budget-svms/samples$ 
ubgpu@ubgpu:~/github/bagged-budget-svms/samples$ 

ubgpu@ubgpu:~/github/bagged-budget-svms/samples$ echo $PYTHONPATH
/usr/local/lib/python3.4/dist-packages:/usr/local/lib/python2.7/dist-packages
ubgpu@ubgpu:~/github/bagged-budget-svms/samples$

**Comment by jclevesque** [comment]
I see you have added the dist-packages manually for both python2 and python3 in PYTHONPATH. This seems to be what's causing the issue. Python should add the /usr/local/lib/pythonX/dist-packages directory automatically to sys.path at runtime. Try clearing the $PYTHONPATH variable, if it works you can edit you bashrc (or whatever file it is set in).

**Comment by andyyuan78** [comment]
great~!

ubgpu@ubgpu:~/github/bagged-budget-svms/samples$ PYTHONPATH="/usr/local/lib/python3.4/dist-packages" python3 a9a.py
Training classifier 0.
Training classifier 1.
Training classifier 2.
Training classifier 3.
Training classifier 4.
Training classifier 5.
Training classifier 6.
Classifier 1 trained.
Classifier 2 trained.
Classifier 6 trained.
Classifier 4 trained.
Classifier 5 trained.
Classifier 3 trained.
Classifier 0 trained.
/usr/local/lib/python3.4/dist-packages/bbsvm/budgetedsvm-predict -z 50000 -v 1 a9a_test.txt output/bsgd_model_c0 output/bsgd_output_c0
/usr/local/lib/python3.4/dist-packages/bbsvm/budgetedsvm-predict -z 50000 -v 1 a9a_test.txt output/bsgd_model_c1 output/bsgd_output_c1
/usr/local/lib/python3.4/dist-packages/bbsvm/budgetedsvm-predict -z 50000 -v 1 a9a_test.txt output/bsgd_model_c2 output/bsgd_output_c2
/usr/local/lib/python3.4/dist-packages/bbsvm/budgetedsvm-predict -z 50000 -v 1 a9a_test.txt output/bsgd_model_c3 output/bsgd_output_c3
/usr/local/lib/python3.4/dist-packages/bbsvm/budgetedsvm-predict -z 50000 -v 1 a9a_test.txt output/bsgd_model_c4 output/bsgd_output_c4
/usr/local/lib/python3.4/dist-packages/bbsvm/budgetedsvm-predict -z 50000 -v 1 a9a_test.txt output/bsgd_model_c5 output/bsgd_output_c5
/usr/local/lib/python3.4/dist-packages/bbsvm/budgetedsvm-predict -z 50000 -v 1 a9a_test.txt output/bsgd_model_c6 output/bsgd_output_c6
Tested budgeted SVM on given dataset, accuracy : 0.7921
Tested budgeted SVM on given dataset, accuracy : 0.7847
Tested budgeted SVM on given dataset, accuracy : 0.7683
Tested budgeted SVM on given dataset, accuracy : 0.8053
Tested budgeted SVM on given dataset, accuracy : 0.7956
Tested budgeted SVM on given dataset, accuracy : 0.7771
Tested budgeted SVM on given dataset, accuracy : 0.7706999999999999
Testing BSGD ensemble: acc: 0.8234. 

ubgpu@ubgpu:~/github/bagged-budget-svms/samples$

**Comment by manvirvirk** [comment]
How to install budgetedSVM toolbox in python?
